GET http://localhost:8000/users

###
POST http://localhost:8000/
Content-Type:  application/json

{
    "email": "silvasebastian2703@gmail.com",
    "password":"clave123"
}

###
GET  http://localhost:8000/users
Content-Type:"application/json"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOjgwMDAvc2VydmVyX2p3dCIsInN1YiI6MSwianRpIjoiZTZjZGNhMTAtZGNhOS00NTM4LWJkZjktNzI4ZGRlNThjYTVkIiwiZXhwIjoxNzQ5MDQ1ODAwfQ.z_2kvZaEKv4gB1Xcil87x3hPoKX8PbiIZJpjFWodM3A